# Change these first
owner: tousleshoraires # Your GitHub organization or username, where this repository lives
repo: uptime-rr # The name of this repository

sites:
  - name: ReineRouge.fr
    url: https://reinerouge.fr
  - name: Documentation
    url: https://support.reinerouge.fr
  - name: Compte Démo
    url: https://demo.reinerouge.fr
  - name: Compte TLH
    url: https://tlh.reinerouge.fr
  - name: Tracking - Europe 1
    url: https://tkg1.reinerouge.fr
  - name: Tracking - Europe 2
    url: https://tkg2.reinerouge.fr
  - name: Tracking - Europe 3
    url: https://tkg3.reinerouge.fr
  - name: Tracking - Europe 4
    url: https://tkg4.reinerouge.fr
  - name: Tracking - Europe 6
    url: https://tkg6.reinerouge.fr
  - name: Tracking - Europe 8
    url: https://tkg8.reinerouge.fr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime-rr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ReineRouge - Overview
  introTitle: "Etat des systèmes."
  introMessage: Surveillance des différents sites et systèmes Reine Rouge. [**Informations**](https://reinerouge.fr)
  navbar:
    - title: Status
      href: /
    - title: Informations
      href: https://reinerouge.fr
    - title: Support
      href: https://support.reinerouge.fr
robotsText: "User-agent: * \n Disallow: /"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
